### ISSUE TITLE
Plugin Theme Overrides Userstyle.css?

### ISSUE THREAD

**Issue by MrPoetry** [andrejilderda/joplin-macos-native-theme#45]
I love the macos native theme, but I want to change the rendered markdown font family & size. I have a simple userstyle.css file:

body {
	font-size: 13pt !important;
	font-family: "Times New Roman";
}

Before I installed this plugin, the above few lines sufficed. Now when I start Joplin, I see the rendered markdown panel flash what looks like my chosen font, and then within a split-second the macos-native-theme default font appears. Am I doing something wrong?

**Comment by andrejilderda** [comment]
Hi @MrPoetry , the CSS the plugin appends has higher specificity than `body` and thus overrides your styles. Could you try:
```css
#rendered-md {
  font-size: 13pt !important;
  font-family: "Times New Roman" !important;
}
```

That should do it!
