### ISSUE TITLE
When using macos theme “extra’s “ added to userstyle.css don’t work!

### ISSUE THREAD

**Issue by BobWs** [andrejilderda/joplin-macos-native-theme#81]
Hi,
I’m new to Joplin, just migrated from Standardnotes, and trying to find my why in the Joplin world☺️
I like your theme as it suits my needs and using a mac, but unfortunately some things don’t work for me as they should.

For example when I activate your theme all the extra codes I have put in userstyle.css don’t work anymore. (Changes found here: https://discourse.joplinapp.org/t/share-your-css/1730/93

But when I disable the macos theme everything works again. 
Could you help me with this problem?

TIA
**example what I have put in the userstyle** 
```
b-gray, b-green, b-red, b-blue, b-orange, b-pink, b-purple {
    width: 90%;
    display: block;
    margin-left: 20px; 
    padding: 10px;
    border: 1px solid;
    border-left: 5px solid;
    border-radius: 2px; 
    word-wrap: break-word;
    box-shadow: 3px 3px 7px 0 rgba(0,0,0,0.3) ; 
}


b-gray {
    border-color: #b1bcc2;
    background-color: #e9edf0; 
 }

b-green {
    border-color: #5fa04e;
    background-color: #c5e5b4; 
} 


b-red {
    border-color: #f65354;
    background-color: #fad3d4; 
}

b-blue {
    border-color: #229ade;
    background-color: #bbe5fb; 
}

b-orange {
    border-color: #cf7506;
    background-color: #faf3d3; 
}


b-purple {
    border-color: #af74e8;
    background-color: #ead9fb; 
}

b-pink {
    border-color: #ed5393;
    background-color: #fad3e5; 
}
```

**Comment by andrejilderda** [comment]
Hi @BobWs , since the way styles are configured in Joplin I had to write a lot of high specificity CSS in order to overwrite the default styles. These probably overwrite your custom styling. What you can try is to add `!important` the rules that don't work, or to all rules:

```css
b-gray,
b-green,
b-red,
b-blue,
b-orange,
b-pink,
b-purple {
  width: 90% !important;
  display: block !important;
  margin-left: 20px !important;
  padding: 10px !important;
  border: 1px solid !important;
  border-left: 5px solid !important;
  border-radius: 2px !important;
  word-wrap: break-word !important;
  box-shadow: 3px 3px 7px 0 rgba(0, 0, 0, 0.3) !important;
}

b-gray {
  border-color: #b1bcc2 !important;
  background-color: #e9edf0 !important;
}

b-green {
  border-color: #5fa04e !important;
  background-color: #c5e5b4 !important;
}

b-red {
  border-color: #f65354 !important;
  background-color: #fad3d4 !important;
}

b-blue {
  border-color: #229ade !important;
  background-color: #bbe5fb !important;
}

b-orange {
  border-color: #cf7506 !important;
  background-color: #faf3d3 !important;
}

b-purple {
  border-color: #af74e8 !important;
  background-color: #ead9fb !important;
}

b-pink {
  border-color: #ed5393 !important;
  background-color: #fad3e5 !important;
}
```

It's not so pretty, but should work. 😅
